/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/building.glb
*/

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { Button } from "antd";
import { useDome, useIsEagle } from "../stores";

export function Building(props) {
  const { nodes, materials } = useGLTF("/building.glb");
  const [isEagle, toggleEagle] = useIsEagle((state) => [
    state.isEagle,
    state.toggleEagle,
  ]);
  const [toggleDome, setDomeName] = useDome((state) => [
    state.toggleDome,
    state.setDomeName,
  ]);

  function handleClick(name) {
    setDomeName(name);
    toggleDome(true);
    toggleEagle(false);
  }

  return (
    <group {...props} dispose={null}>
      <group position={[-271.53, -15.8, 712.13]} rotation={[0, 0.06, 0]}>
        <Html>
          <Button
            onClick={() => handleClick("wuchongta")}
            size="small"
            className="glass"
          >
            五重塔
          </Button>
        </Html>
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919"].geometry}
          material={materials.gujian_Mtl002_submtl5}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_1"].geometry}
          material={materials.gujian_Mtl002_submtl10}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_2"].geometry}
          material={materials["hq0007.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_3"].geometry}
          material={materials["hq0008.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_4"].geometry}
          material={materials["Mat3d66-4734923-65-64013.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_5"].geometry}
          material={materials["hq0010.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_6"].geometry}
          material={materials["Mat3d66-4734923-65-64013.005"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_7"].geometry}
          material={materials["hq0011.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_8"].geometry}
          material={materials["hq0012.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_9"].geometry}
          material={materials["Mat3d66-4734923-3-71695.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_10"].geometry}
          material={materials["Mat3d66-4734923-4-71095.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_11"].geometry}
          material={materials["Mat3d66-4734923-5-26748.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_12"].geometry}
          material={materials["hq0014.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_13"].geometry}
          material={materials["hq0015.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_14"].geometry}
          material={materials["hq0016.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_15"].geometry}
          material={materials["hq0017.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_16"].geometry}
          material={materials["hq0019.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_17"].geometry}
          material={materials["hq0020.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_18"].geometry}
          material={materials["hq0021.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_19"].geometry}
          material={materials["hq0022.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_20"].geometry}
          material={materials["hq0023.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_21"].geometry}
          material={materials["Mat3d66-4734923-65-64013.006"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_22"].geometry}
          material={materials["hq0024.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_23"].geometry}
          material={materials["hq0025.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1344117-13-919_24"].geometry}
          material={materials["hq0026.001"]}
        />
      </group>
      <group
        position={[-393.4, -46.79, -475.39]}
        rotation={[2.97, 1.31, -2.99]}
        scale={0.67}
      >
        <Html>
          <Button
            onClick={() => handleClick("chucheng")}
            size="small"
            className="glass"
          >
            楚城
          </Button>
        </Html>
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001"].geometry}
          material={materials["Mat3d66-4700324-16-1654.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_1"].geometry}
          material={materials.wall}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_2"].geometry}
          material={materials.wall}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_3"].geometry}
          material={materials["Mat3d66-627105-13-293.002"]}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_4"].geometry}
          material={materials["Mat3d66-1448218-5-1236.002"]}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_5"].geometry}
          material={materials["Mat3d66-1448218-3-5589.002"]}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_6"].geometry}
          material={materials["Mat3d66-627105-11-824.002"]}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_7"].geometry}
          material={materials["Mat3d66-627105-13-293.008"]}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_8"].geometry}
          material={materials["Mat3d66-1448218-3-5589.008"]}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_9"].geometry}
          material={materials["Mat3d66-627105-11-824.008"]}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_10"].geometry}
          material={materials["Mat3d66-1448218-5-1236.007"]}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_11"].geometry}
          material={materials["Mat3d66-1448218-6-272.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_12"].geometry}
          material={materials["GN-建筑-标准玻璃"]}
        />
        <mesh
          geometry={nodes["Obj3d66-4700324-16-103001_13"].geometry}
          material={materials["JN_building_001_UV01_Fin.001"]}
        />
      </group>
      <group
        position={[109.47, 28.82, -111.48]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[6.29, 6.29, -3.32]}
      >
        <Html>
          <Button
            onClick={() => handleClick("chutiantai")}
            size="small"
            className="glass"
          >
            楚天台
          </Button>
        </Html>
        <mesh
          geometry={nodes["Obj3d66-1292453-7-446002"].geometry}
          material={materials["JN_building_001_UV01_Fin.002"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1292453-7-446002_1"].geometry}
          material={materials["JN_building_001_UV01_Fin.004"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1292453-7-446002_2"].geometry}
          material={materials["JN_building_001_UV01_Fin.005"]}
        />
      </group>
      <mesh
        geometry={nodes.离骚碑.geometry}
        material={materials["材质.001"]}
        position={[336.72, -12.57, -144.27]}
        scale={[5.44, 11.21, 3.56]}
      >
        <Html>
          <Button
            onClick={() => handleClick("lisaobei")}
            size="small"
            className="glass"
          >
            离骚碑
          </Button>
        </Html>
      </mesh>
      <group position={[-444.4, 27.68, -202.13]} scale={[0.97, 0.88, 0.97]}>
        <mesh
          geometry={nodes["Obj3d66-1448218-8673-132"].geometry}
          material={materials["Mat3d66-1448218-5-1236.017"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1448218-8673-132_1"].geometry}
          material={materials["Mat3d66-1448218-3-5589.019"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1448218-8673-132_2"].geometry}
          material={materials["Mat3d66-627105-13-293.016"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1448218-8673-132_3"].geometry}
          material={materials["Mat3d66-627105-11-824.019"]}
        />
      </group>
      <group
        position={[-464.81, 32.1, -211.72]}
        rotation={[0.01, -0.01, 0]}
        scale={2.09}
      >
        <Html>
          <Button
            onClick={() => handleClick("zhubeiting")}
            size="small"
            className="glass"
          >
            朱碑亭
          </Button>
        </Html>
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17"].geometry}
          material={materials["Mat3d66-1273285-199-8051.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_1"].geometry}
          material={materials["Mat3d66-1273285-211-2838"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_2"].geometry}
          material={materials["Mat3d66-1273285-215-2913"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_3"].geometry}
          material={materials["Mat3d66-1273285-216-6322"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_4"].geometry}
          material={materials["Mat3d66-1273285-217-4294"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_5"].geometry}
          material={materials["Mat3d66-1273285-218-2134"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_6"].geometry}
          material={materials["Mat3d66-1273285-200-4520.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_7"].geometry}
          material={materials["Mat3d66-1273285-198-3636.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_8"].geometry}
          material={materials["Mat3d66-1273285-201-2752.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_9"].geometry}
          material={materials["Mat3d66-1273285-202-8410.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_10"].geometry}
          material={materials["Mat3d66-1273285-203-9410.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_11"].geometry}
          material={materials["Mat3d66-1273285-204-6276.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_12"].geometry}
          material={materials["Mat3d66-1273285-205-4794.001"]}
        />
        <mesh
          geometry={nodes["Obj3d66-1273285-7890-17_13"].geometry}
          material={materials["Mat3d66-4700324-16-1654"]}
        />
      </group>
      <mesh
        geometry={nodes.古建06.geometry}
        material={materials["JN_building_001_UV01_Fin.007"]}
        position={[-178.77, -39.35, -381.08]}
        rotation={[-Math.PI, 0.38, -Math.PI]}
        scale={1.61}
      />
      <mesh
        geometry={nodes.古建06001.geometry}
        material={materials["JN_building_001_UV01_Fin.007"]}
        position={[-155.53, -43.23, -382.04]}
        rotation={[0, -0.31, 0]}
        scale={1.61}
      />
      <mesh
        geometry={nodes.古建06002.geometry}
        material={materials["JN_building_001_UV01_Fin.007"]}
        position={[-281.72, -48.19, -469.21]}
        rotation={[-Math.PI, 0.82, -Math.PI]}
        scale={2.24}
      />
      <mesh
        geometry={nodes.古建07002.geometry}
        material={materials["JN_building_001_UV01_Fin.008"]}
        position={[-210.69, -34.13, -393.91]}
        rotation={[-3.13, 0.55, -3.04]}
        scale={1.54}
      />
      <mesh
        geometry={nodes.古建_房子11001.geometry}
        material={materials.JN_building_001_UV01_Fin}
        position={[-217.16, -32.86, -398.1]}
        rotation={[0.11, 0.75, -0.08]}
        scale={[2.11, 1.7, 2.11]}
      />
      <mesh
        geometry={nodes.古建_房子11002.geometry}
        material={materials.JN_building_001_UV01_Fin}
        position={[-211.27, -33.6, -404.74]}
        rotation={[-Math.PI, -1, -Math.PI]}
        scale={[2.11, 1.7, 2.11]}
      />
      <mesh
        geometry={nodes.古建_房子11003.geometry}
        material={materials.JN_building_001_UV01_Fin}
        position={[-109.09, -38.71, -341.1]}
        rotation={[0, -0.99, 0]}
        scale={[2.11, 1.7, 2.11]}
      />
      <mesh
        geometry={nodes.古建_房子11004.geometry}
        material={materials.JN_building_001_UV01_Fin}
        position={[-253.91, -38.13, -434.45]}
        rotation={[0, 0.61, 0]}
        scale={[2.11, 1.7, 2.11]}
      />
      <mesh
        geometry={nodes.古建_房子11005.geometry}
        material={materials.JN_building_001_UV01_Fin}
        position={[-243.99, -35.36, -423.34]}
        rotation={[0, 0.87, 0]}
        scale={[2.11, 1.7, 2.11]}
      />
      <mesh
        geometry={nodes.古建_房子11006.geometry}
        material={materials.JN_building_001_UV01_Fin}
        position={[-243.75, -37.66, -435.82]}
        rotation={[-Math.PI, -0.74, -Math.PI]}
        scale={[2.11, 1.7, 2.11]}
      />
      <mesh
        geometry={nodes.古建_房子11007.geometry}
        material={materials.JN_building_001_UV01_Fin}
        position={[-235.21, -33.48, -415.64]}
        rotation={[0, 0.87, 0]}
        scale={[2.11, 1.7, 2.11]}
      />
      <mesh
        geometry={nodes.古建_房子11008.geometry}
        material={materials.JN_building_001_UV01_Fin}
        position={[-237.86, -35.98, -429.73]}
        rotation={[-Math.PI, -0.74, -Math.PI]}
        scale={[2.11, 1.7, 2.11]}
      />
      <mesh
        geometry={nodes.古建_房子18001.geometry}
        material={materials["JN_building_001_UV01_Fin.006"]}
        position={[-248.8, -36.91, -429.43]}
        rotation={[0, 0.64, 0]}
        scale={1.44}
      />
      <mesh
        geometry={nodes.古建_房子18002.geometry}
        material={materials["JN_building_001_UV01_Fin.006"]}
        position={[-192.68, -37, -390.38]}
        rotation={[Math.PI, -0.98, Math.PI]}
        scale={1.44}
      />
      <mesh
        geometry={nodes.古建_房子18003.geometry}
        material={materials["JN_building_001_UV01_Fin.006"]}
        position={[-194.24, -36.57, -383.36]}
        rotation={[0, 0.97, 0]}
        scale={1.44}
      />
      <mesh
        geometry={nodes.古建_房子18004.geometry}
        material={materials["JN_building_001_UV01_Fin.006"]}
        position={[-205.47, -34.53, -398.78]}
        rotation={[Math.PI, -1.1, Math.PI]}
        scale={1.44}
      />
      <mesh
        geometry={nodes.古建_房子18005.geometry}
        material={materials["JN_building_001_UV01_Fin.006"]}
        position={[-232.76, -34.86, -423.43]}
        rotation={[Math.PI, -0.85, Math.PI]}
        scale={1.44}
      />
      <mesh
        geometry={nodes.古建_房子18006.geometry}
        material={materials["JN_building_001_UV01_Fin.006"]}
        position={[-173.73, -43.29, -396.28]}
        rotation={[0, -1, 0]}
        scale={1.44}
      />
    </group>
  );
}

useGLTF.preload("/building.glb");
