/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/compass.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { getCameraRotateDeg } from "../helpers/camera-helper";

export function Compass(props) {
  const { nodes, materials } = useGLTF("/compass.glb");
  const dial = useRef();

  useFrame((state, delta) => {
    const deg = getCameraRotateDeg(state.camera);
    dial.current.rotation.z = deg;
    // console.log(getCameraRotateDeg(state.camera));
  });

  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -1.57, 0]} scale={0.1}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={40}>
          <mesh
            geometry={nodes.compass_baseMerged_M_Compass_BigPieces_0.geometry}
            material={materials.M_Compass_BigPieces}
          />
          <mesh
            geometry={nodes.compass_baseMerged_M_Compass_SmallPieces_0.geometry}
            material={materials.M_Compass_SmallPieces}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={40}>
          <mesh
            geometry={nodes.compass_bezel_M_Compass_BigPieces_0.geometry}
            material={materials.M_Compass_BigPieces}
          />
          <mesh
            geometry={nodes.compass_bezel_M_Compass_Glass_0.geometry}
            material={materials.M_Compass_Glass}
          />
        </group>
        <group
          position={[-129.77, 43.61, 0]}
          rotation={[Math.PI / 2, -1.31, Math.PI]}
          scale={40}
        >
          <mesh
            geometry={nodes.compass_coverMerged_M_Compass_BigPieces_0.geometry}
            material={materials.M_Compass_BigPieces}
          />
          <mesh
            geometry={
              nodes.compass_coverMerged_M_Compass_SmallPieces_0.geometry
            }
            material={materials.M_Compass_SmallPieces}
          />
        </group>
        <group
          position={[131.42, 25.18, 0]}
          rotation={[-Math.PI / 2, 0.96, Math.PI / 2]}
          scale={40}
        >
          <mesh
            geometry={nodes.compass_rearSight_M_Compass_BigPieces_0.geometry}
            material={materials.M_Compass_BigPieces}
          />
          <mesh
            geometry={nodes.compass_rearSight_M_Compass_Glass_0.geometry}
            material={materials.M_Compass_Glass}
          />
        </group>
        <mesh
          ref={dial}
          geometry={nodes.compass_floatingDial_M_Compass_SmallPieces_0.geometry}
          material={materials.M_Compass_SmallPieces}
          position={[0, 54.72, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[43.34, 43.34, 40.18]}
        />
        <mesh
          geometry={nodes.compass_thumbLoop_M_Compass_SmallPieces_0.geometry}
          material={materials.M_Compass_SmallPieces}
          position={[131.42, 25.18, 0]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={4000}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/compass.glb");
