/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/ground.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Ground(props) {
  const { nodes, materials } = useGLTF("/ground.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.area.geometry}
        material={materials.地面}
        position={[-573.32, -64.65, 1378.41]}
        rotation={[0, -0.07, 0]}
      />
      <mesh
        geometry={nodes.way.geometry}
        material={materials["材质.003"]}
        position={[-0.8, -0.06, -3]}
        rotation={[0, -0.07, 0]}
      />
      <mesh
        geometry={nodes.road.geometry}
        material={materials["材质.004"]}
        position={[-814.51, 1792.37, 424.09]}
        rotation={[0, -0.07, 0]}
        scale={137.98}
      />
      <mesh
        geometry={nodes.level.geometry}
        material={materials["材质.005"]}
        position={[-573.32, -54.5, 1378.41]}
        rotation={[0, -0.07, 0]}
        scale={-2237.69}
      />
    </group>
  );
}

useGLTF.preload("/ground.glb");
