/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/groundwater.glb
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useDome } from "../stores";

export const Plane = forwardRef((props, gref) => {
  const { nodes, materials } = useGLTF("/groundwater.glb");
  const isDome = useDome((state) => state.isDome);
  return (
    <group {...props} dispose={null} ref={gref} visible={!isDome}>
      <mesh
        geometry={nodes.研究区域.geometry}
        material={materials.地面}
        position={[-586.32, -61.16, 1372.67]}
        rotation={[0, -0.01, 0]}
      />
      <mesh
        geometry={nodes.水面.geometry}
        material={materials["材质.007"]}
        position={[-586.32, -54.5, 1372.67]}
        rotation={[0, -0.01, 0]}
        scale={-2237.69}
      />
    </group>
  );
});

useGLTF.preload("/groundwater.glb");
