/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/way.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Way(props) {
  const { nodes, materials } = useGLTF('/way.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.way.geometry} material={materials.wayMaterial} position={[-0.8, -0.06, -3]} rotation={[0, -0.07, 0]} />
    </group>
  )
}

useGLTF.preload('/way.glb')
