/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/ground.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/ground.gltf");
  return (
    <group {...props} dispose={null} position={[0, -100, 0]}>
      <mesh geometry={nodes.reprojected.geometry} material={materials.ground} />
    </group>
  );
}

useGLTF.preload("/ground.gltf");
